name: contract-analysis
channels:
  - conda-forge  # Prioridad a conda-forge para versiones más nuevas
  - defaults
dependencies:
  - python=3.11  # 3.11 or 3.12 for spaCy compatibility
  - pandas=2.2.2
  - scikit-learn=1.6.1
  - numpy=2.0.2
  - matplotlib=3.10.0
  - seaborn=0.13.2
  - spacy=3.8.7
  - nltk=3.9
  - pillow=11.2.1
  - redis-py=5.0.8
  - psycopg2=2.9.7
  - pip
  - pip:
    - Django==5.2.3
    - djangorestframework==3.15.2
    - django-cors-headers==4.3.1
    - drf-spectacular==0.27.2
    - python-decouple==3.8
    - celery==5.3.4
    - python-multipart==0.0.9
    - joblib==1.5.1
    - pytest-django==4.8.0
    - factory-boy==3.3.0 