# Generated by Django 5.2.3 on 2025-07-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clause",
            name="gpt_explanation",
            field=models.TextField(
                blank=True, help_text="Explicación del análisis GPT"
            ),
        ),
        migrations.AddField(
            model_name="clause",
            name="gpt_is_abusive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clause",
            name="gpt_is_valid_clause",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="clause",
            name="gpt_suggested_fix",
            field=models.TextField(
                blank=True, help_text="Sugerencia de corrección de GPT"
            ),
        ),
    ]
