# Generated by Django 5.2.3 on 2025-07-07 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_clause_gpt_explanation_clause_gpt_is_abusive_and_more"),
    ]

    operations = []
