# Generated by Django 5.2.3 on 2025-07-09 23:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_auto_20250706_2135"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clause",
            name="confidence_score",
            field=models.FloatField(
                default=0.0,
                help_text="Confianza del modelo ML (0-1)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
    ]
