# Generated by Django 5.2.3 on 2025-07-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0004_alter_clause_confidence_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clause",
            name="gpt_explanation",
            field=models.TextField(
                blank=True, help_text="Explicación del análisis GPT", null=True
            ),
        ),
        migrations.AlterField(
            model_name="clause",
            name="gpt_suggested_fix",
            field=models.TextField(
                blank=True, help_text="Sugerencia de corrección de GPT", null=True
            ),
        ),
    ]
