# Generated by Django 5.2.3 on 2025-07-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0005_alter_clause_gpt_explanation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clause",
            name="clause_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("payment", "Pago"),
                    ("duration", "Duración"),
                    ("obligations", "Obligaciones"),
                    ("termination", "Terminación"),
                    ("dispute_resolution", "Resolución de Disputas"),
                    ("other", "Otro"),
                ],
                default="general",
                max_length=50,
            ),
        ),
    ]
