# Generated by Django 5.2.3 on 2025-07-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0006_alter_clause_clause_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clause",
            name="clause_number",
            field=models.TextField(
                blank=True, help_text="Número o título de la cláusula"
            ),
        ),
    ]
