# Generated by Django 5.2.3 on 2025-08-12 03:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_alter_clause_clause_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('executive_summary', models.TextField(help_text='Resumen ejecutivo del análisis legal')),
                ('affected_laws', models.TextField(help_text='Leyes y regulaciones afectadas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_analysis', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Análisis Legal',
                'verbose_name_plural': 'Análisis Legales',
            },
        ),
    ]
