# Generated by Django 5.2.3 on 2025-08-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_legalanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalanalysis',
            name='affected_laws',
            field=models.JSONField(help_text='Leyes y regulaciones afectadas'),
        ),
        migrations.AlterField(
            model_name='legalanalysis',
            name='executive_summary',
            field=models.JSONField(help_text='Resumen ejecutivo del análisis legal'),
        ),
    ]
