# Generated by Django 5.2.3 on 2025-08-27 00:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Número secuencial del artículo')),
                ('tema', models.CharField(help_text='Tema principal (ej: alquileres, compraventa)', max_length=100)),
                ('articulo', models.CharField(help_text='Número del artículo del Código Civil (ej: 1708, 1594-1595)', max_length=50)),
                ('contenido', models.TextField(help_text='Contenido completo del artículo')),
                ('ley_asociada', models.CharField(help_text='Ley específica asociada (ej: Ley 4314, Ley 108-05)', max_length=100)),
                ('keywords', models.JSONField(default=list, help_text='Palabras clave extraídas automáticamente para búsqueda')),
                ('embedding_vector', models.JSONField(blank=True, help_text='Vector de embeddings para búsqueda semántica (768 dimensiones)', null=True)),
                ('relevance_score', models.FloatField(default=1.0, help_text='Puntuación de relevancia para análisis de contratos (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_active', models.BooleanField(default=True, help_text='Artículo activo para búsquedas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artículo Legal',
                'verbose_name_plural': 'Artículos Legales',
                'ordering': ['numero'],
                'indexes': [models.Index(fields=['numero'], name='legal_knowl_numero_1f1580_idx'), models.Index(fields=['tema'], name='legal_knowl_tema_fd75ee_idx'), models.Index(fields=['articulo'], name='legal_knowl_articul_1005b3_idx'), models.Index(fields=['ley_asociada'], name='legal_knowl_ley_aso_033a0d_idx'), models.Index(fields=['relevance_score'], name='legal_knowl_relevan_3c3b2c_idx'), models.Index(fields=['is_active'], name='legal_knowl_is_acti_70b442_idx')],
                'unique_together': {('articulo', 'ley_asociada')},
            },
        ),
        migrations.CreateModel(
            name='LegalKnowledgeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_hash', models.CharField(help_text='Hash MD5 de la consulta', max_length=64, unique=True)),
                ('query_text', models.TextField(help_text='Texto original de la consulta')),
                ('tema_context', models.CharField(blank=True, help_text='Tema de contexto', max_length=100)),
                ('generated_response', models.TextField(help_text='Respuesta generada por el LLM')),
                ('articles_used', models.JSONField(default=list, help_text='Artículos utilizados en la respuesta')),
                ('confidence_score', models.FloatField(help_text='Nivel de confianza de la respuesta', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('hit_count', models.IntegerField(default=0, help_text='Número de veces que se ha usado este cache')),
                ('expires_at', models.DateTimeField(help_text='Fecha de expiración del cache')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cache de Conocimiento Legal',
                'verbose_name_plural': 'Cache de Conocimiento Legal',
                'ordering': ['-last_used'],
                'indexes': [models.Index(fields=['query_hash'], name='legal_knowl_query_h_0f376e_idx'), models.Index(fields=['tema_context'], name='legal_knowl_tema_co_eaa9c3_idx'), models.Index(fields=['expires_at'], name='legal_knowl_expires_e139f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='RAGSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(help_text='Consulta original del usuario')),
                ('tema_filtro', models.CharField(blank=True, help_text='Tema usado como filtro', max_length=100)),
                ('articles_found', models.JSONField(default=list, help_text='IDs de artículos encontrados')),
                ('similarity_scores', models.JSONField(default=list, help_text='Puntuaciones de similitud')),
                ('search_method', models.CharField(choices=[('embedding', 'Búsqueda por Embeddings'), ('keyword', 'Búsqueda por Palabras Clave'), ('tema', 'Búsqueda por Tema'), ('hybrid', 'Búsqueda Híbrida')], default='hybrid', max_length=20)),
                ('was_helpful', models.BooleanField(blank=True, help_text='¿Fue útil la búsqueda?', null=True)),
                ('response_time', models.FloatField(blank=True, help_text='Tiempo de respuesta en segundos', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historial de Búsqueda RAG',
                'verbose_name_plural': 'Historial de Búsquedas RAG',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tema_filtro'], name='legal_knowl_tema_fi_95b5e1_idx'), models.Index(fields=['search_method'], name='legal_knowl_search__c7c58a_idx'), models.Index(fields=['-created_at'], name='legal_knowl_created_14fa7e_idx')],
            },
        ),
    ]
