# Generated by Django 5.2.3 on 2025-08-08 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text='Número de teléfono', max_length=20)),
                ('organization', models.CharField(blank=True, help_text='Organización o empresa', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Biografía o descripción')),
                ('avatar', models.ImageField(blank=True, help_text='Foto de perfil', null=True, upload_to='avatars/')),
                ('is_verified', models.BooleanField(default=False, help_text='Usuario verificado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
